test = {   'name': 'q6b',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> len(find_rich_neighborhoods(training_data_cleaned, 5, np.median)) == 5\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> isinstance(rich_neighborhoods, list)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> all([isinstance(neighborhood, str) for neighborhood in rich_neighborhoods])\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': ">>> set(rich_neighborhoods) == set(['StoneBr', 'NridgHt', 'NoRidge']) # Check to see if correct neighborhoods identified\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': ">>> set(find_rich_neighborhoods(training_data_cleaned, 2, np.min)) == set(['GrnHill', 'NoRidge'])\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
