test = {   'name': 'q7b',
    'points': 2,
    'suites': [   {   'cases': [   {   'code': ">>> sum(training_data_qu['Fireplace_Qu'] == 'No Fireplace') == 975 # Make sure you've replaced all the missing values with 'No Fireplace'\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> sum(training_data_qu.loc[:, 'Fireplace_Qu'].isnull() == 0) == 1998 # Make sure you haven't introduced anything strange\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': ">>> sum(training_data_qu.loc[:, 'Fireplace_Qu'] == 'Excellent') == 30\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
