test = {   'name': 'q7a',
    'points': 2,
    'suites': [   {   'cases': [   {'code': ">>> bool(re.search(rt_re, 'hi rt hello'))\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> bool(re.search(rt_re, 'rt'))\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> bool(re.search(rt_re, 'rt hello'))\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> bool(re.search(rt_re, 'hello rt'))\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> bool(re.search(rt_re, 'rthello')) == False\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> bool(re.search(rt_re, 'hellort')) == False\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> bool(re.search(rt_re, ':rt'))\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> bool(re.search(rt_re, 'rt:'))\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> bool(re.search(hash_link_re, '#hello'))\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> bool(re.search(hash_link_re, 'hello#')) == False\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> bool(re.search(hash_link_re, '#')) == False\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> bool(re.search(hash_link_re, '#!')) == False\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> bool(re.search(hash_link_re, '#HELLO'))\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> bool(re.search(hash_link_re, 'http'))\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> bool(re.search(hash_link_re, '')) == False\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> bool(re.search(hash_link_re, 'httphttp'))\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
